[package]
authors = ["daratao"]
description = "overlay sale for usdc pair"
edition = "2021"
name = "ovl-sale-ccd-public"
version = "0.2.2"

[features]
crypto-primitives = ["concordium-std/crypto-primitives"]
default = ["std"]
std = ["concordium-std/std", "concordium-cis2/std"]
wasm-test = ["concordium-std/wasm-test", "concordium-std/concordium-quickcheck"]

[dependencies]
concordium-cis2 = "3.0.0"
concordium-std = { version = "6.1.0", default-features = false }
sale-utils = { path = "../sale-utils" }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
opt-level = "s"

[dev-dependencies]
concordium-std = { version = "6.1.0", features = ["concordium-quickcheck"] }
