[package]
authors = ["daratao"]
description = "overlay sale for usdc pair"
edition = "2021"
name = "ovl-sale-ccd-public"
version = "0.2.0"

[features]
crypto-primitives = ["concordium-std/crypto-primitives"]
default = ["std"]
std = ["concordium-std/std", "concordium-cis2/std"]

[dependencies]
concordium-cis2 = "3.0.0"
concordium-std = "6.0.0"
sale-utils = {path = "../sale-utils"}

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
opt-level = "s"

[dev-dependencies]
concordium-std = {version = "6.0.0", features = ["concordium-quickcheck"]}
